In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a[1])

[1 2 3]
2


advantages of numpy array over python list

--> occupies less memory

--> faster

--> more convenient

In [9]:
import sys

l=range(1000)
print(sys.getsizeof(1)*len(l))
arr=np.arange(1000)
print(arr.size*arr.itemsize)

28000
4000


python list taking 28000 bytes because size of one item is 28 bytes

numpy array taking 4000 bytes because size of one item is 4 bytes

In [10]:
import time
SIZE=10000000
l1=range(SIZE)
l2=range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)
# for python list
start=time.time()
res=[(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# for numpy array
start=time.time()
res=a1+a2
print("numpy array took: ",(time.time()-start)*1000)

python list took:  913.693904876709
numpy array took:  112.98632621765137


this proves numpy array is faster

In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
