In [14]:
import numpy as np
arr1=np.array([5,6,7])
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr1.ndim)
print(arr2.ndim)
print(arr2.itemsize)
print(arr2.dtype)
arr2=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2)
print(arr2.size)
print(arr2.shape)
arr2=np.array([[1,2],[3,4],[5,6]], dtype=complex)
print(arr2)

1
2
4
int32
float64
8
[[1. 2.]
 [3. 4.]
 [5. 6.]]
6
(3, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [20]:
print(np.zeros((3,2)))
print(np.ones((3,2)))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.linspace(1,6,10))
print(np.linspace(1,6,5))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4 5]
[1 3 5]
[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]
[1.   2.25 3.5  4.75 6.  ]


In [30]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr.shape)
print(arr.reshape(2,3))
print(arr.reshape(6,1))
print(arr.ravel())
print(arr)
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(np.sqrt(arr))
print(np.std(arr)) # standard deviation

(3, 2)
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
1
6
21
[ 9 12]
[ 3  7 11]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


In [34]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1.dot(arr2)) # matrix product

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
