In [14]:
import numpy as np
a=np.array([5,6,7])
print(a[0:2])
print(a[-1])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1,2])
print(b[0:2,2])
print(b[-1,0:2])
print(b[:,1:])
for row in b:
    print(row)
for row in b:
    for elm in row:
        print(elm)
for elm in b.flat:
    print(elm)

[5 6]
7
6
[3 6]
[7 8]
[[2 3]
 [5 6]
 [8 9]]
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [18]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [23]:
a=np.arange(30).reshape(2,15)
print(a)
print(np.vsplit(a,2))
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [27]:
a=np.arange(12).reshape(3,4)
print(a)
print(a>4)
print(a[a>4])
a[a>4]=-1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
