In [4]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
for elm in np.nditer(a,order='C'): # C order
    print(elm)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for elm in np.nditer(a,order='F'): # Fortran order
    print(elm)

0
4
8
1
5
9
2
6
10
3
7
11


In [7]:
for elm in np.nditer(a, order='F', flags=['external_loop']):
    print(elm)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [8]:
for elm in np.nditer(a, op_flags=['readwrite']): 
    elm[...]=elm*elm
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [15]:
b=np.arange(3,15,4).reshape(3,1)
print(b)
for x,y in np.nditer([a,b]): # to do this --> dimension should be same or --> one dimension should be 1
    print(x,y)               # here row dimension same and one col dimension is 1, so broadcastable

[[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
